# Generated by Django 6.0.1 on 2026-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
